DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS url;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE url (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER,
  short_url TEXT NOT NULL,
  long_url TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);